### ISSUE TITLE
Issue on Kindle Fire 7

### ISSUE THREAD

**Issue by bluesisgood** [BaronKiko/LauncherHijack#10]
Followed all the directions, but after enabling "To detect home button press" under Settings > Accessibility, it no longer recognizes any buttons / icon presses.  Clicking on anything (icons, home button, etc.) causes the screen to blink and then do nothing.  No apps will load, can't get into settings, bottom buttons don't work.

I thought I was hosed, and that I'd have to restore from a backup, but I was able to finally get back into settings by holding down the home button long enough for voice command to work and I got into settings that way.  Once settings launched, I was able to navigate around and turn off the "To detect home button press."

Running Fire OS 5.4.0.1.

**Comment by BaronKiko** [comment]
Odd one. I can't quite look into it atm but try setting a launcher before you enable to service in settings.
Also if you want to get back to settings open the app switcher to get there or slide down from the top and click settings. If it really is locked up you can use a USB cable and adb to uninstall it remotely, just google uninstalling and app through adb.
If that doesn't help then I can have a look see into it in a couple days probably

**Comment by BaronKiko** [comment]
Oh and to be clear it has been tested on 5.4.0.1 so there is no reason it shouldn't work.

**Comment by H3rmit** [comment]
not working for my fire 7 either. i can tell its TRYING to work but 98% of the time it dont work.

**Comment by wolfsstolz** [comment]
ok, i have a Fire 7 Tab too and it works sometimes for me.
If i click one time on home button it stay with nova launcher, if i click 2 times it go back to FireOS. The Problem is that it switch back to FireOS and it make problems that it go not to start screen, then it switch back to fireOS.
The App is working 66% maybe but i have FireOS 5.4.0 installed.

**Comment by BaronKiko** [comment]
After multiple attempts I am unable to replicate this issue(s). If I can track it down I can look however that doesn't seem very likely on my device. My only assumption is that I am using an 8" Kindle hd not the 7" but the software should work just the same.
