### ISSUE TITLE
widgets on fire hd 8?

### ISSUE THREAD

**Issue by fidget-tetrahedron** [BaronKiko/LauncherHijack#12]
the hijack works great. on home button press, there's only a half-second flash of the Kindle ui before the launcher kicks in. thing is, it won't let me use any widgets. it redirects me to the kindle settings. is this because i can't make nova the default? or some other, fixable reason? i'd really love to be able to put a clock and some other stuff on the home screen.

**Comment by BaronKiko** [comment]
This doesn't do anything to do with widgets. Widgets are available with the default fire launcher and the open launcher by default however there is an adb command you can run that lets you use any launcher. Just Google something like "widgets on any launcher fire OS" and it should come up.
