### ISSUE TITLE
Doesn't work on Fire TV v3

### ISSUE THREAD

**Issue by Poincare1** [BaronKiko/LauncherHijack#13]
On Fire TV v3, when trying to run the app, it just goes to a white screen very quickly (1 second) then does nothing.

**Comment by BaronKiko** [comment]
It's not designed to work on the fire TV.

**Comment by MCTyler** [comment]
Works on my Fire TV Just fine......

**Comment by BaronKiko** [comment]
This is an old issue from before firetv support was added. It does indeed now work.
