### ISSUE TITLE
Virustotal result on V3 APK

### ISSUE THREAD

**Issue by arrrlaska** [BaronKiko/LauncherHijack#15]
A little concerned that VirusTotal [found](https://www.virustotal.com/#/file/96aba1538e125af1da68344d61524964575044ae34c7d9c5f2e562ff65133865/detection) 2 potential issues.

Perhaps this is typical, I'm not sure. Just thought I'd raise it.
Thanks!

**Comment by BaronKiko** [comment]
Honestly doesn't surprise me that much, messing with the home buttons functionality is pretty sketcy. All I can say is it's not a virus, it's a false positive.

**Comment by arrrlaska** [comment]
Figured as much. It was only 2 out of 61 engines, scanners which I'd never heard of before.
Thanks for responding! 😄
