### ISSUE TITLE
LauncherHijack with Fire OS 5.6.2.0 Problem?

### ISSUE THREAD

**Issue by pixelpop13** [BaronKiko/LauncherHijack#17]
Updated my Fire HD 10 OS to 5.6.2.0 today and the notification and navigation areas became invisible and non-functional. The Amazon tech did a factory refresh to correct the problem. I had Google Play, LauncherHijack, Nova Launcher and a clock/weather widget installed (in addition to some play store apps).

This is just a note that LauncherHijack may cause an issue with this OS update.

**Comment by BaronKiko** [comment]
I haven't done the update however the code deffinatly doesn't mess with the notification area.
As for the navigation area I did make a version that overlayed the home button to do the hijack but I think it was iffy enough that it never made it here. Even so the worst the app could do to the buttons is stop them from working, not remove them.
Basically to me it sounds like a fire os issue and likely has nothing to do with my app. I will leave the issue open for a little bit for any other reports.

**Comment by pixelpop13** [comment]
Thanks for the quick reply. I'm going to reinstall Nova and LauncherHijack and let you know the results.

**Comment by BaronKiko** [comment]
Hopefully it works, they haven't put the update out for my device (hd 8) so I can't even test it. Please let me know if it works out.

**Comment by renfri89** [comment]
Hi, so my tablet also had the same issue, it updated to 5.6.2.0 today and the notification bar, home button went missing. I uninstalled the hijacker app and restarted the tablet, once it turned on I found out the update was not fully done. A screen appeared asking to connect to a wifi network to finish update and once I did that a video was showed about the new show feature it has. Anyways after the video was done the home button was back, reinstalled hijacker app and everything is working again.

**Comment by pixelpop13** [comment]
I have reinstalled everything and have no problems, so my initial problem remains a mystery, I and the Amazon tech did do several restarts trying to correct the issue to no avail. But I do wonder now if I had uninstalled LauncherHijack and tried a restart (before doing a factory reset) if I could have gotten to the same point as renfri89 without doing a factory reset, Is there a chance that LauncherHijack prevents complete installation of the update, even tho it appears that the update was successful?

**Comment by BaronKiko** [comment]
While I doubt launcher hijack would stop the update it is deffinatly possible if the device needs to use the default launcher during update. If that's the case then simply disabling launcher hijack in accessibility setting during the install should help.
If somebody can confirm this then I will update the read me to make it clear.

**Comment by BaronKiko** [comment]
I'm pretty sure you can't downgrade an Amazon device without rooting it and even then its not easy.
I wouldn't worry about it. Once they push the update for my device I can test but others may see this post when they update and they could test simply disabling launcher hijack.

**Comment by pixelpop13** [comment]
Yeah, I knew it would be difficult. I only got the 5.6.1.0 update, so it's not the entire OS. But I do have 5.6.1.0, so if anyone asks for it.

Now, on a related note...when you go into Show Mode, the display rotates horizontal and it's locked to that one horizontal orientation. This means that if I (and a bunch of others) try to use the third-party case I bought for it as a stand, the display will (likely) be upside down. And I can't turn the tablet around in the case because the cutouts are then in the wrong place. So if you are so inclined, you might try to make a fix for that (maybe incorporate into hijack). :-)

**Comment by BaronKiko** [comment]
That's totally out of the scope of this discussion or launcher hijack as a whole. it is also something I don't have the time or interest to solve.

**Comment by pixelpop13** [comment]
OK, sorry. I didn't mean to overstep any boundaries or upset you, I appreciate the work you've done on hijack and wish you all the best.

**Comment by jsonger** [comment]
It looks like the upgrade itself it disabling the notification and nav bars until the fire launcher runs a post-upgrade process that includes playing a video about Show Mode.

If you could detect first boot after an upgrade and not hijack the launcher on that one reboot, it would probably solve the problem for the future.

**Comment by BaronKiko** [comment]
Makes sense, unfortunately I don't really know how you could detect that scenario without a lot of work and bloat in the application. Even then I'm not sure its even possible but there is probably a way. Regardless I think I'm just going to have to call it unfixable and just add a comment to the readme about disabling launcherhijack during updates. Seems kinda lazy but if I tried to fix it the application would probably suffer for this very specific scenario.
Will leave this issue open for now in case somebody has something else to add but it will most likely be closed soonish.
Thanks for the detective work guys.

**Comment by BaronKiko** [comment]
I have updated the read me and the XDA post to mention these findings. Hopefully that's enough to close this one off.
Thank you guys for helping me investigate.
