### ISSUE TITLE
Crash in AccServ when NO launchers are detected

### ISSUE THREAD

**Issue by Speeddymon** [BaronKiko/LauncherHijack#21]
This is low priority, it was encountered on an unsupported (by you) device (my Android phone) -- feel free to close it as a wontfix. I figured I would report it and let you decide. It might possibly be good to fix for the fire phone

After figuring out how to bind AccServ to the Accessibility Service via adb for the FireTV devices, I encountered a repeating crash after I did the below:

Uninstalled all of my test launchers
Reinstalled LauncherHijack
Bound the service in Accessibility

To define "repeating", what I mean is that the AccServ kept crashing every time I would click to dismiss the Force Close prompt, causing another Force Close prompt -- so, I disabled the service binding, installed a couple of test launchers again, and then went about enabling the binding again, after which I got no crashes.

**Comment by BaronKiko** [comment]
:( More of an issue that thought. Will try fix.

**Comment by Speeddymon** [comment]
Idk that it necessarily needs fixing, so much as just a warning during first launch, and make sure that the selected launcher is started at each boot.

**Comment by Speeddymon** [comment]
An alternative "fix" would be to make the firetv launcher selectable within the app as one of the launchers. Might be worthwhile to do anyway in case someone wants to get back to stock while performing troubleshooting, etc.

**Comment by BaronKiko** [comment]
It's developed into a worse bug. Now when enabling the accessibility service it totally locks up the device if you don't select a launcher first. It should open Launcher Hijack if you haven't selected an app, ie prompting you to select one.
You can select the default launcher if you uncheck hide system apps and launchers only but if you really want to revert you should just disable the service or uninstall the app.

**Comment by Speeddymon** [comment]
apologies, you're right. I am trying to get ADB connected to my cube right now to test on this too for you so a bit of a split-brain

**Comment by BaronKiko** [comment]
Fixed
