### ISSUE TITLE
new firestick

### ISSUE THREAD

**Issue by sterno1966** [BaronKiko/LauncherHijack#22]
we need an update for the new firestick it crashes as soon as you launch it

**Comment by BaronKiko** [comment]
Sadly I dont have a fire stick and I'm still trying to fix fire TV/cube support. Life has been getting in the way.
If you can get the reason it crashes via adb I can atleast try judge how bad it is. If it's something very simple I can probably do something about it soon, anything more complex could be a while.

**Comment by basxto** [comment]
I can start the app after doing `pm grant com.baronkiko.launcherhijack android.permission.SYSTEM_ALERT_WINDOW`, but `Settings -> Accessibility -> To detect home button press` is missing on fire TV stick 4k.
Sometimes it work when I press the home button, sometimes it goes to the original launcher.

**Comment by BaronKiko** [comment]
You can enable the service via adb with:
# adb shell settings get enabled_accessibility_services
Copy the output from the above command and paste it into the command below
# adb shell settings put enabled_accessibility_services (PASTE_HERE):com.baronkiko.launcherhijack/com.baronkiko.launcherhijack.AccServ

How that helps

**Comment by BaronKiko** [comment]
Did this fix the issues you guys have been having?

**Comment by basxto** [comment]
```
Invalid namespace 'enabled_accessibility_services'
```
`settings` wants a namespace and no namespace has this key.
Maybe they completly removed this.

**Comment by basxto** [comment]
I already tried the secure namespace, it does not look like it’s supported on fireOS.
The key was not defined and creating it does not look like making any difference.
```
$ adb shell settings get secure enabled_accessibility_services
null
$ adb shell settings put secure enabled_accessibility_services com.baronkiko.launcherhijack/com.baronkiko.launcherhijack.AccServ
$ adb shell settings get secure enabled_accessibility_services 
com.baronkiko.launcherhijack/com.baronkiko.launcherhijack.AccServ
```

```
adb shell settings list secure  | grep -i accessibility
AccessibilitySettings.version=2
accessibility_captioning_enabled=0
accessibility_display_magnification_auto_update=1
accessibility_display_magnification_enabled=0
accessibility_display_magnification_mode=0
accessibility_display_magnification_scale=2.0
accessibility_enabled=1
accessibility_script_injection=0
accessibility_script_injection_url=https://ssl.gstatic.com/accessibility/javascript/android/AndroidVox_v1.js
accessibility_web_content_key_bindings=0x13=0x01000100; 0x14=0x01010100; 0x15=0x02000001; 0x16=0x02010001; 0x200000013=0x02000601; 0x200000014=0x02010601; 0x200000015=0x03020101; 0x200000016=0x03010201; 0x200000023=0x02000301; 0x200000024=0x02010301; 0x200000037=0x03070201; 0x200000038=0x03000701:0x03010701:0x03020701;
enabled_accessibility_services=com.baronkiko.launcherhijack/com.baronkiko.launcherhijack.AccServ
```

**Comment by BaronKiko** [comment]
Umm, I don't think you can create keys like that. You get invalid namespace as you discovered earlier so you are setting it. It just happened to be null by default.



Without an accessibility service the app is severely limited. V3 should just about work if you enable the system alert window but you will have to launch the app manually every time you reboot the device.
Even then it will probably be very inconsistent.

What version of fireos are you using? Probably won't help me much but it's nice to know.....

**Comment by BaronKiko** [comment]
Well my firetv is on fireos 6.2.5.5 (NS6255/1628)
Home version 6.1.1.0-120

Not sure if it has updated since I last used it but I can atleast debug it if I find time.

In light of this info I'm going to close this issue as it falls under the preexisting issue "add support for fire TV devices". Most of the info regarding it is on the pull request. It's not an easy one. We managed to get it kinda working. You couldn't use the long press menu or access settings while it was running as they are all under the same application. In my mind that's broken. Speedymon chose to live without those features as he installed a 3rd party settings app that could do a couple basic things.

I have since had some thoughts on how to get around this but it requires some work to implement.

**Comment by BaronKiko** [comment]
I made a test release for the fireTV, latest post here: https://github.com/BaronKiko/LauncherHijack/pull/20
Maybe it will help your device, give it a go and leave feedback there if you get a chance. Thanks

**Comment by sterno1966** [comment]
hey thanks but the home button not working
