### ISSUE TITLE
No effect on Kindle Fire 7

### ISSUE THREAD

**Issue by demonicsandwich** [BaronKiko/LauncherHijack#26]
I have a Kindle Fire 7 running FireOS 5.4.0.0, and the app doesn't seem to work for me. It installed fine, and it doesn't give any errors when I run it and select Nova Launcher. It just simply doesn't make any changes.

**Comment by davidfi01** [comment]
Did you activate the accessibility setting for home button?

**Comment by demonicsandwich** [comment]
Yes.

**Comment by demonicsandwich** [comment]
A hard reset fixed it.
