### ISSUE TITLE
No power off with fire hdx anymore

### ISSUE THREAD

**Issue by mhofer2011** [BaronKiko/LauncherHijack#29]
After update to 4.02 from 3.0 to Power off my fire hdx is not possible anymore. 

Regards,

Mario

**Comment by BaronKiko** [comment]
Does disabling the accessibility service allow you to power off? I don't touch the power button so no idea why it wouldn't work.
Also what version of Fire OS are you on?

**Comment by BaronKiko** [comment]
Any update on this?

**Comment by BaronKiko** [comment]
No updates and can't reproduce so closing.

**Comment by BaronKiko** [comment]
#31 Is the place for this bug now.
