### ISSUE TITLE
Hijack Launcher V.4.0.2 - Kids Launcher

### ISSUE THREAD

**Issue by lambrosfl** [BaronKiko/LauncherHijack#30]
Hello and thank you for creating Hijack Launcher,
While Hijack Launcher works great on Amazon Fire 8" 6.3.0.1  (2018 - 8th gen.), it doesn't work for several Kids Launchers such as iWawa, Kid's Shell, Kid's Home, etc. I tried about 5-6 different kids launchers without success. It seems that many people bought the specific tablet on Black Friday for their kids, but everybody is facing the same issue with Kid's launchers. 
It will be much appreciated if you can check the possibility for an updated Hijack Launcher that supports kid's launchers.
Kind Regards
Lambros

**Comment by BaronKiko** [comment]
Had a quick look at the apps provided and honestly there is nothing I can do to help. They all require certain perms and/or to be the default launcher. Amazon restricts setting the launcher so it will always be the default fire one when an application asks. Launcher Hijack uses 4 methods to capture the home press, no need for details, Once it detects a home press it basically just opens it as if you were to open it from the default home screen. So this will work with anything you can open manually from the home screen. None of the apps listed work when opened.

Something important to note is this isn't 100% for everybody. It's works 100% for me but it only takes 1 failure for your child to get to the default launcher, at least until they press home again.

There a 2 options you can take that I can think of:
1. stick with the default parental control in the os (you may be albe to do more through adb but I am no expert)
2. Ask the developers of these apps to remove the requirement for default launcher.

Either way I can't do anything. I'm closing this as it's not an issue with Launcher Hijack. You can still comment if you have any other questions but I have no children and tablets only became a thing after I was responsible so I really don't know much about kids stuff.
Best of luck.

**Comment by lambrosfl** [comment]
Thank you for the info and for your support.
I will try and let you know.
Kind Regards,
Lambros
