### ISSUE TITLE
can't turn off tablet .

### ISSUE THREAD

**Issue by joshuaorgeron** [BaronKiko/LauncherHijack#31]
when i hold the power button and the ok and cancel buttons appear pressing ok does not turn of the tablet.

**Comment by BaronKiko** [comment]
Can you get some logs? This issue has come up a couple times and I can't replicate it on any devices I own. Also if you open settings in launcher hijack does turning any options off stop the issue?
Fyi with Christmas and new years I will probably be slow to respond so please bare with me.

**Comment by BaronKiko** [comment]
Ok sure, others have had the same issue as you can see by the referenced issues so I will leave this open to gather more info. Feel free to unsubscribe if you have no interest.

**Comment by joshuaorgeron** [comment]
I think it's just nova launcher that does this i fixed it by installing any other launcher that wasn't nova launcher.

**Comment by BaronKiko** [comment]
Is there anyone that can confirm installing another launcher fixes the issue?

**Comment by BaronKiko** [comment]
No update, closing issue

**Comment by DarkWizarD24** [comment]
I have the same issues. I try with Nova launcher, Lawnchair 2 and Niagara lancher. I have the bug on the three.
To solve it, I have to stop the Launcher Hijack with the application menu. Then the shutdown works as intendeed.
But its not very convenient.
