### ISSUE TITLE
Can't turn off tablet.  

### ISSUE THREAD

**Issue by shilesmcgee** [BaronKiko/LauncherHijack#32]
Can't turn off tablet utilizing button.   Also, I have the Google play store side loaded.  This caused the play store to not be accessible.  Once I uninstalled LauncherHijack, I was able to turn off tablet and access Play Store.

Fire HD 10
5.6.1.0

**Comment by BaronKiko** [comment]
Closing as this is the same issue as #31 
Was only just opened before you but regardless please check there.
