### ISSUE TITLE
no on for detect home button

### ISSUE THREAD

**Issue by fatmando66** [BaronKiko/LauncherHijack#33]
"to detect home button" button doesnt have a switch to turn it on

**Launcher Hijack Version and Device**
fire 8

**Comment by BaronKiko** [comment]
Not a lot of info to go on here. Can you provide a screenshot?
Also as an fyi I'm pretty busy atm with Christmas and new years coming up so please bare with my slow responses.

**Comment by Moreno420** [comment]
![screenshot_20181225-175330](https://user-images.githubusercontent.com/46139971/50427453-57902500-086e-11e9-97e9-d4ef02d24842.png)
![screenshot_20181225-175335](https://user-images.githubusercontent.com/46139971/50427454-64147d80-086e-11e9-94aa-b4676f6b7d0c.png)

The installation instructions say:

Open settings and navigate to "Accessibility -> To detect home button press" and press enable

But there is no switch or button to press

there's no way to enable it on my new Fire HD 8 tablet

**Comment by markstricker** [comment]
I have the exact same issue.  To add, though, when I installed the APK file, I go a message saying "Accessible services are off".  I don't know what that means, as the interface allows you to turn other accessiblity services on or off.

**Comment by BaronKiko** [comment]
The plot thickens. Do you know of any apps that have services that work?  Ideally open source so I can see how they do it.

**Comment by OppressorMan** [comment]
Same thing here as listed above.

**Comment by OppressorMan** [comment]
My Fire rolled out an update and i tried the Hijacker again and it worked. sorry about that i should have checked my version of the OS was Current.

**Comment by Moreno420** [comment]
My tablet updated also! Seems to have fixed that issue.

**Comment by tde5** [comment]
I am having the same issue as everyone else with the non-option to toggle Accessibility Services. I have another app installed that requires Accessibility Services, so I've already used ADB Shell to enable that app. My problem is if I enable LauncherHijack, it toggles the other (previously enabled via ADB) service off. I can't have more than one Accessibility Service enabled at a time, and I'm not well versed enough with ADB shell to enable Accessibility for two services with one command. Any tips? Thanks in advance.

**Comment by uKER** [comment]
My case is even worse than described here.
I'm on a Fire TV Stick Gen. 2 with OS version 5.2.6.8, and when I enter System\Accessibility, the "To detect home button" option just isn't there.
I have run the adb shell command to enable the accessibility service, but launching Launcher Hijack still says the service is disabled, and needless to say, the home button on the remote keeps launching the Amazon launcher.
Any ideas?

![img_20190104_024833](https://user-images.githubusercontent.com/8409373/50675246-912e0200-0fcb-11e9-916f-aa828122e415.jpg)

**Comment by BaronKiko** [comment]
Well I really should have followed up sooner. It seems to be a system bug with tablets so just update.
For the firetv instructions are clearly detailed in the instructions.

**Comment by uKER** [comment]
As I mentioned in my post, I do follow the instructions, enabling the accessibility service over ADB, but it still says it's not enabled.

**Comment by BaronKiko** [comment]
> As I mentioned in my post, I do follow the instructions, enabling the accessibility service over ADB, but it still says it's not enabled.

Try using this command with the other one:
`settings put secure accessibility_enabled 1`

**Comment by uKER** [comment]
> Try using this command with the other one:
> `settings put secure accessibility_enabled 1`
Success at last! That did it.
You may want to add that info to the HELP.md
Thanks!
