### ISSUE TITLE
No Launchers In List

### ISSUE THREAD

**Issue by pscbimmer** [BaronKiko/LauncherHijack#35]
Fire HD7 (4th Gen) FireOS 5.6.1.0 Launcher Hijack 4.0.2

Nothing appears in the list of launchers after installing. I've rebooted, uninstalled and re-installed, tried installing Launcher Hijack 3.0. and have never seen a list of launchers.

![screenshot_2019-01-05-12-18-53](https://user-images.githubusercontent.com/46403620/50727257-7308f480-10e6-11e9-83dd-a6d19c3f60e5.png)

**Comment by Gibil** [comment]
I have similar results with HD8 5th gen.  In the list of launchers, it just says "Hello World."  Evie should be listed.

**Comment by BaronKiko** [comment]
Sorry I didn't get back to you sooner. Very odd, can you get any apps to show with the options in the menu, something like show system apps and launchers only?

**Comment by pscbimmer** [comment]
I can get my apps to show by de-selecting "Launchers Only", but no Launchers ever show. And I can see system apps with my apps if I also de-select "Hide System Apps". 

If I de-select "Hide System Apps" and select "Launchers Only" I get two options. First is called Home Pages (com.amazon.firelauncher) and Settings (com.android.settings)

**Comment by BaronKiko** [comment]
Are your launchers on the list when you display everything? I have had issues with launchers being categorised correctly as it's up to the launcher to declare itself as one.

**Comment by pscbimmer** [comment]
It's working now. I reinstalled again and rebooted a couple times and for what ever reason the launchers are listed.

**Comment by BaronKiko** [comment]
Strange, ah well will close the issue as it's probably not normal. Glad it's working.

**Comment by EasternPA** [comment]
I just experienced this yesterday on an HD8 5th gen. I installed the Google Now launcher and could never get it to show up. I also installed Nova free and then both showed up. I selected Google Now and it worked. I uninstalled Nova free and Google Now continued working fine.
