### ISSUE TITLE
Logo for Hijack Launcher v4.0.2 app. I want to help create it

### ISSUE THREAD

**Issue by urbanman2004** [BaronKiko/LauncherHijack#36]
Just like it's stated in the title, I would like to help create a logo for your Hijack Launcher v4.0.2 app. I would've sent a PM, but I couldn't find an option available, and you stated on XDA that you don't check the forum much often. I have the same username on XDA so feel free to message me here or on there so I know how you want to proceed moving forward.

**Comment by BaronKiko** [comment]
Sorry I didn't get back to you sooner. You are more than welcome to try something, As long as it doesn't look like a toddler drew it I will probably use it :P

**Comment by urbanman2004** [comment]
Not a problem. What do you want in it or what should it depict, and I can go from there. Any further ideas feel free to shoot them to me

**Comment by BaronKiko** [comment]
It should probably relate to the Amazon but something more generic would be good as this app keeps expanding in scope. Maybe just a simple LH or something?
Generally it's up to you, if I knew how to design stuff i would have made an icon long ago. It should follow the design spec for icons, it would be classed as a legacy launcher icon: https://developer.android.com/guide/practices/ui_guidelines/icon_design

**Comment by urbanman2004** [comment]
Alright thanks. I have a few concepts regarding that "HL" idea you threw out there. I should have a professional grade one done in no later than 2 weeks

**Comment by urbanman2004** [comment]
Sorry buddy for the hiatus. I have a few rough sketches of some ideas I came up with. Do you have some sort of email I can send them to you

**Comment by BaronKiko** [comment]
Sorry I missed this. You can email me at andy.075109@hotmail.co.uk but I don't really check it often so you should probably just post here.

**Comment by urbanman2004** [comment]
> Sorry I missed this. You can email me at [andy.075109@hotmail.co.uk](mailto:andy.075109@hotmail.co.uk) but I don't really check it often so you should probably just post here.

I'll send it to you via email sometime tonight. Are you on Skype or Whatsapp by chance

**Comment by BaronKiko** [comment]
No, I only use discord for messaging.
If that's better for you I can send you my details over email. I don't really want to post them here :)

**Comment by urbanman2004** [comment]
Alright... I'll email you right now

**Comment by BaronKiko** [comment]
It is done, closing issue
