### ISSUE TITLE
Not working - adb: not found

### ISSUE THREAD

**Issue by Animizio** [BaronKiko/LauncherHijack#39]
Hey,
I can install the app and also open it.
But all the adb codes won't work, I just get a adb: not found back.
I m using Firetv Stick 4k with FireOS 6.2.5.8
Please fix it.. I was so happy to use a custom launcher on it..

**Comment by BaronKiko** [comment]
You need to get a copy of ADB to run. There is nothing I can fix here, there are many tutorials out there that will help you.

**Comment by Animizio** [comment]
Sorry, but what means "get a copy of adb to run"? Do I have to transfer adb to my Firetv stick?

**Comment by Animizio** [comment]
Okay i got it.. Not working with smartphone adb apps. With computer it works fine, good job and thanks! :)
