### ISSUE TITLE
Issue w/ Fire 10 tablet

### ISSUE THREAD

**Issue by jessetbowman** [BaronKiko/LauncherHijack#40]
Running with Nova launcher on Amazon Fire HD 10 tablet. Installed in December w/o issue but has started 'flickering'. It looks like it's trying to flip b/w the default Fire launcher and Nova.  Tablet works after deleting hijack but the default Fire launcher is garbage and un-friendly for toddlers. I haven't tried another launcher yet but will when she lets me (lol). Will update if it resolves the issue.

**Comment by BaronKiko** [comment]
You can try to go through the setup again. It sounds like the accessibility service is disabled.  
If that doesn't help go into the launcher hijack app, go into setting then reset to default.  
Finally if that doesn't work send me a list of what settings are enabled

**Comment by dalewking** [comment]
Was able to go into settings to uninstall the app and then go through set up again and have been working since.

The accessibility setting was set. The issue was not that it wasn't going to hijack, but more that Amazon detected the hijack and went to it's home screen which hijack detected and redirected to my selected launcher and back and forth every few seconds.

**Comment by BaronKiko** [comment]
Very strange, but glad you got it working.
Hopefully op is able to solve their issue too

**Comment by jessetbowman** [comment]
I appreciate it, guys. I haven't had a chance to try it again, but I may just go with the default launcher since my little one is doing fine with it. I appreciate all the work and will definitely use it if I get another Amazon device for myself.

**Comment by dalewking** [comment]
May be coincidence, but I had also gone through the steps to disable the special offers on the launch screen, but Amazon managed to put them back at the same time that this started happening. And those same steps to disable the special offers no longer works.

Perhaps Amazon is upping the arms race to make sure you have an inferior tablet experience.

**Comment by BaronKiko** [comment]
You probably just had a system update which brings the ads back.
Anyway as one of you had it fixed and the other is no longer interested in fixing I'm going to close this issue.
