### ISSUE TITLE
When turning off Fire TV (Power Button) System Re-Awakes to Home Menu

### ISSUE THREAD

**Issue by MCTyler** [BaronKiko/LauncherHijack#41]
**Describe the bug**
Probably not a way around this but I want to make my Fire TV "Spouse" Proof so when she Presses the power button on Fire TV that it launches Kodi which I have set on Boot and Kodi is configured to automatically tune the last channel she was viewing. App works as advertised on "Boot" But not Power, (Sleep). Is there any way to add this functionality? 
**"Home" Button Works Perfect by the Way going Straight to Kodi TV Guide!**

**To Reproduce**
1. Press Power button on Fire TV Remote (Off)
2. Press Power button on Fire TV Remote (on)
3. Home Menu appears and is not the desired outcome

**Expected behavior**
I would like Kodi to simply resume Playing channel she last exited from when Powering the Fire TV off

**Launcher Hijack Version and Device**
V402

**Logs**
Not sure where I would find the Logs.....App works perfect, just resuming from Power Off (Sleep) to Home Menu is not the desired outcome.

**Screenshots**
None

**Additional context**
N/A

**Comment by BaronKiko** [comment]
Hmm, my remote doesn't have a power button.
Not sure if it would be possible to fix, or worth it if possible. You can just press the home button after it's booted to get back to kodi.

**Comment by MCTyler** [comment]
I told the Wife about "Home" Button and it did indeed work as intended for her this morning. You can close this if you like.

**Comment by BaronKiko** [comment]
Glad you got it working.
