### ISSUE TITLE
BaronKiko how do i compile this?

### ISSUE THREAD

**Issue by itoikenza** [BaronKiko/LauncherHijack#42]
why the heck does github never have ready to install apps? exe's or apk's? i hate it. I'm not a fan of this site at all. i am very technically inclined but lazy AF... please don't tell me it's github policy to not provide pre-compiled shiz!

**Comment by itoikenza** [comment]
i have a fireTVstick 2, on latest firmware... btw.

**Comment by BaronKiko** [comment]
Almost all githubs provide precomplied versions, you can get the latest release here: https://github.com/BaronKiko/LauncherHijack/releases
You can get the releases page for any repo using this button: https://puu.sh/D7Mtn/dc0797cbb6.png
If you still want to build it for some reason you can grab the repo and build it with android studio
