### ISSUE TITLE
BaronKiko is it possible to set any given launcher to home button?

### ISSUE THREAD

**Issue by itoikenza** [BaronKiko/LauncherHijack#43]
i would love to use nova launcher but i can't use a wallpaper. any fix? also can you guide me to which app can make nova be bound to "home"? i like Halauncher too but i wanna know if Hal can set a wallpaper image? sorry if I'm asking for help on apps you don't administer!

**Comment by BaronKiko** [comment]
I can't help with other apps. All launcher hijack does is open another application when you press the home button or it detects the default launcher opening. If it's not doing that make sure you have read the instructions.

**Comment by Hunter9888x** [comment]
Could use a button mapper
