### ISSUE TITLE
LauncherHijack Tasker Task

### ISSUE THREAD

**Issue by Hunter9888x** [BaronKiko/LauncherHijack#44]
start launcher hijack
Accessibility service through tasker app

Directly on fire tv
With no other device needed

Need adb debugging enabled
With tasker & adb shell tasker plugin

Launcherhijack Tasker Task Backup
Import in tasker app & start task
https://mega.nz/#!6PJDlCRT!cQQR-DiVG9xNmZROdThYPi5M8olFjEGRalW69nwX3XA

Can use mouse toggle for android tv version
be sure to go in launcherhijack settings
Enable disable on menu long press

Disable mouse toggle by hold menu & press home button

Tasker App
https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm

ADB Shell Command Tasker Plugin
https://play.google.com/store/apps/details?id=com.ADBPlugin

**Comment by BaronKiko** [comment]
Please don't spam this across this GitHub.
I don't see why your would want to do this or why you feel the need to post about it here.

**Comment by Hunter9888x** [comment]
Why
You can enable
Accessibility service
Directly on fire tv
With no other device needed

**Comment by BaronKiko** [comment]
Right, see it's hard for me to know that when you just post a link to an automation app with no extra information.
From my understanding of permissions I doubt it's actually enabling the service but I will take a look when I get time.
Regardless I doesn't warrent it being posted in 3 seperate places

**Comment by Hunter9888x** [comment]
Tested it myself it works
Need adb debugging enabled
With tasker & adb shell tasker plugin

**Comment by Hunter9888x** [comment]
I don't understand
Why wouldn't it have the permission
adb debug is natively supported on fire tv
can run adb commands Directly on fire tv  
Tested by me it works
