### ISSUE TITLE
Amazon has now blocked LauncherHijacker. It is "uninstalled" from my Fire HD10 tablet and will not reload. I read of a renamed file called Launcher.Hijack.v.4..0.4.b.43.Clone.apk, which is located at mediafire.com and claims to be a renamed .apk that will work on Amazon. But my browser sends up flashing lights and sirens and won't let me download it--Norton says it's poison. Do you have a solution?  LauncherHijack with Nova Launcher worked fine for many months--until today.

### ISSUE THREAD

**Issue by CountrySquire** [BaronKiko/LauncherHijack#47]
Before submitting any issues please ensure you have read all instructions in the ReadMe and checked your issue hasn't already been submitted in the issues section. Please delete this header and fill out as many sections as possible.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Launcher Hijack Version and Device**
Your device and installed version

**Logs**
Any logs associated with the issue

**Screenshots**

**Additional context**

**Comment by cw76** [comment]
XDA-Developers thread about it here:  https://forum.xda-developers.com/amazon-fire/general/launcher-root-launcher-hijack-v2-t3561026/page40

Appears Amazon's latest update added a block for the APK name.  For my 2017 Fire HD 8, it is running Fire OS 5.6.4.0 (636558520) installed on April 26, 2019, though, somehow, it just started failing for me yesterday (April 29).  I briefly saw a pop-up on the bottom of the screen say that Hijack Launcher was blocked (but it was brief and I accidentally dismissed it very quickly as I was just tapping around when it popped up).

It'd be great to get an official updated release with a new name to resolve this issue!  Thanks for your work on this app!

**Comment by reedbl1** [comment]
I can verify that this is true.  I came into my office this morning to a message on my fire tablet that LauncherHijack no longer works with the table.

**Comment by ek49ten** [comment]
I too can confirm this. Tried to update to the latest release and got the same message. It's to hard to upload the screenshot from this stupid thing. Launcherhijack is not compatible with this device blah blah.

**Comment by Basti-Fantasti** [comment]
Can confirm this, too

**Comment by Hunter9888x** [comment]
Try Appcloner to clone app
https://appcloner.app

**Comment by k1ngstire** [comment]
Appcloner did work. Renamed it to Launcher Hijakk and Works fine now. Thanks

**Comment by SwiCago** [comment]
Amazon has now also blocked the HD8
But can confirm, using app cloner works for now.

**Comment by Guiorgy** [comment]
I tried renaming the app (see my fork) and I confirm that it works on Fire OS 6.3.0.1

**Comment by Johnnyshanley** [comment]
Someone commented on my video and he gave me a link and worked fine
Link https://www.mediafire.com/file/kqa89yndk468itf/Launcher.Hijack.v.4.0.3.b.43.Clone.apk/file

**Comment by Johnnyshanley** [comment]
WARNING: linker: /data/data/com.gmail.heagoo.apkbuilder/files/bin/aapt: unused DT entry: type 0x6ffffffe arg 0x1d94 WARNING: linker: /data/data/com.gmail.heagoo.apkbuilder/files/bin/aapt: unused DT entry: type 0x6fffffff arg 0x2

**Comment by SOOTTV** [comment]
> https://www.mediafire.com/file/kqa89yndk468itf/Launcher.Hijack.v.4.0.3.b.43.Clone.apk/file

Tried this 6.2.6.4 and it isn't working, is there an adb command you have to run as well?

**Comment by Guiorgy** [comment]
@SoulTV , [here](https://github.com/Guiorgy/Launch3rH1jack/releases/tag/403r) try this?

**Comment by dogtags40** [comment]
Problem is that app requires accessibilities services, and that option is now disabled

**Comment by RedcatPhoenix** [comment]
> > https://www.mediafire.com/file/kqa89yndk468itf/Launcher.Hijack.v.4.0.3.b.43.Clone.apk/file
> 
> Tried this 6.2.6.4 and it isn't working, is there an adb command you have to run as well?

Well, it worked for me, have you uninstalled it?

**Comment by RedcatPhoenix** [comment]
> > > https://www.mediafire.com/file/kqa89yndk468itf/Launcher.Hijack.v.4.0.3.b.43.Clone.apk/file
> > 
> > 
> > Tried this 6.2.6.4 and it isn't working, is there an adb command you have to run as well?
> 
> Well, it worked for me, have you uninstalled it?

Plus, I have a Fire HD8 2017 (6th Gen) so it has the accessibility

**Comment by Oscarwang666** [comment]
SOLVED!!!
get the "Nova Launcher from" Google ap store
(watch half of this video https://www.youtube.com/watch?v=swZdVD_EQIY&t=358s to get Google store and Nova Launcher ) 

1. download the LauncherHijack apk from the follwoing link to your computer (LauncherHijackV403.apk)
https://github.com/BaronKiko/LauncherHijack/releases/download/403/LauncherHijackV403.apk
2. Use a usb cable to save that file to your amazon table 
3. Download this AppCloner from this link and slect the LauncherHijack apk in AppCloner 
[AppCloner.zip](https://github.com/BaronKiko/LauncherHijack/files/4484077/AppCloner.zip)
4. rename "LauncherHijack " to whatever name
5. go to setting -> Accesibility -> Services -> turn botj on"Nova Lanuchr" and "To detect home button pree "

**Comment by CountrySquire** [comment]
I originated this string, and I appreciate the input from everyone. AppCloner does, indeed, work great!  I downloaded LauncherHijackV403.apk, then "cloned" it with AppCloner (which appears to just give the old app a new name and to so indicate in the internal code).  A word of advice:  obviously, Amazon does not like the use of LauncherHijack or anything else that does the same thing. So I assume they'll keep looking for similar "offenders." So I suggest that the new name you give your app is a LOT different than anything to do with "launcher" or "hijack" or any misspelling of these words.  Name it something totally different. And don't report here what you've named it!  Thanks again, everyone.

**Comment by jimmy2lips** [comment]
![26348050-3A6B-45E8-8EB0-38048F8E31CE](https://user-images.githubusercontent.com/71822211/94180628-88462980-fe5b-11ea-8601-5e629a022898.jpeg)
Need help as I get this with launcher hijacked. Even when I clone it and change name. Any way to fix this?
My kindle has updated automatically on me. 
* use to work great and hen had to clone it and it worked and now I’m at a loss. Wish it didn’t update as it’s just caused problems since. Any help is greatly appreciated, thanks!

**Comment by CountrySquire** [comment]
Jimmy,
Please click on this link to lead you to a Dropbox file, which contains the following files:
 Fire  I


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Fire

Shared with Dropbox
 |

 |

 |




 

            The clone LauncherHijack I am using

            Nova Launcher, which Iuse as the default launcher under Launcher Hijack

            AppCloner, which youcan use to clone the Launcher app and give it any name you want

            Fire to Androidinstructions

            Ad removal instructions

 This is how I have converted my Fire to Android. It works great.

 Device is running Fire OS 7.3.1.5

**Comment by jobiegermano** [comment]
> Jimmy, Please click on this link to lead you to a Dropbox file, which contains the following files:  Fire  I | | | | | | | | | | | Fire Shared with Dropbox | | |               The clone LauncherHijack I am using             Nova Launcher, which Iuse as the default launcher under Launcher Hijack             AppCloner, which youcan use to clone the Launcher app and give it any name you want             Fire to Androidinstructions             Ad removal instructions  This is how I have converted my Fire to Android. It works great.  Device is running Fire OS 7.3.1.5

I don’t think the link posted...

**Comment by jimmy2lips** [comment]
> Jimmy, Please click on this link to lead you to a Dropbox file, which contains the following files:  Fire  I | | | | | | | | | | | Fire Shared with Dropbox | | |               The clone LauncherHijack I am using             Nova Launcher, which Iuse as the default launcher under Launcher Hijack             AppCloner, which youcan use to clone the Launcher app and give it any name you want             Fire to Androidinstructions             Ad removal instructions  This is how I have converted my Fire to Android. It works great.  Device is running Fire OS 7.3.1.5

I have used app cloner a few times but it almost like it picking the signature out. However even the clones I have tested don’t seem to work. And in your response there wasn’t a link to click on to test the one your using.

**Comment by kupietools** [comment]
Can confirm, using appcloner to rename is only a temporary solution. It worked for a few minutes, now I am getting the same java error screenshotted above, and I have to manually open Launcher Hijack each time I want another launcher to open. Then a few minutes later, same java error, rinse & repeat. Latest Fire 8 & FireOS.
