### ISSUE TITLE
LauncherHijack v4.0.3 Classic Issue

### ISSUE THREAD

**Issue by RedcatPhoenix** [BaronKiko/LauncherHijack#54]
I used Launcher Hijack to escape from the amazon freetime launcher and when i got classic, it disappeared! So i got a clone! https://www.mediafire.com/file/kqa89yndk468itf/Launcher.Hijack.v.4.0.3.b.43.Clone.apk
AND IT WORKS JUST FINE!!!!
AMAZON DID A GOSH DARN ATTACK!!!!! 😡😡😡😡😡
SO PLEASE FIX THAT PROBLEM!!!!! THE AMAZON FREETIME LAUNCHER SUCKS!!!!!!
AMAZON TABLETS ARE CHEAP WITH ADS IN THE LAUNCHER AND LOCKSCREEN!!!!!!!
I HATE AMAZON TABLETS!!!!!! WHEN MY TABLET IS AT 10% ALL MY APPS CRASH!!!!!!!
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by RedcatPhoenix** [comment]
> I used Launcher Hijack to escape from the amazon freetime launcher and when i got classic, it disappeared! So i got a clone! https://www.mediafire.com/file/kqa89yndk468itf/Launcher.Hijack.v.4.0.3.b.43.Clone.apk
> AND IT WORKS JUST FINE!!!!
> AMAZON DID A GOSH DARN ATTACK!!!!! 
> SO PLEASE FIX THAT PROBLEM!!!!! THE AMAZON FREETIME LAUNCHER SUCKS!!!!!!
> AMAZON TABLETS ARE CHEAP WITH ADS IN THE LAUNCHER AND LOCKSCREEN!!!!!!!
> I HATE AMAZON TABLETS!!!!!! WHEN MY TABLET IS AT 10% ALL MY APPS CRASH!!!!!!!
> REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

Plus the amazon fire needs to banned in the united states and just have kindles!

**Comment by RedcatPhoenix** [comment]
Btw, try https://www.mediafire.com/file/kqa89yndk468itf/Launcher.Hijack.v.4.0.3.b.43.Clone.apk it fixes everything!

**Comment by friedl** [comment]
No need to create this rant and another issue, when this has been discussed in length in other issue threads. Including the solution via clone apps.

Thank you ;)

**Comment by RedcatPhoenix** [comment]
NEXT TIME MAKE LAUNCHER HIJACK 5.0 WORK!
