### ISSUE TITLE
7.3.1.1 Default Launcher Keeps Showing

### ISSUE THREAD

**Issue by stmalk** [BaronKiko/LauncherHijack#57]
LH hardly works on a new Fire HD 10, 9th generation, running 7.3.1.1 fire os. Chosen launcher (Nova) appears after reboot, but Home button brings the default launcher back. It stays like that for 5 seconds or so, then pops back to Nova by itself. Hitting Home button while default launcher is up does nothing.  
Home button detection and Nova option in accessibility settings are both enabled.

**Comment by SimulatedMatter** [comment]
Getting the same issues on my device. I also had to rename the app in android studio to stop it from being deleted

**Comment by lefoy** [comment]
I'm having the same issue

**Comment by mbennoer** [comment]
Hey @stmalk @BeefaloRancher @lefoy have you tried this workaround: https://github.com/BaronKiko/LauncherHijack/issues/52#issuecomment-504738320 ?

**Comment by SimulatedMatter** [comment]
Will do it now and let you know if it fixes it

**Comment by lefoy** [comment]
I ended up using this tool and it worked perfectly with a few more useful
tools like removing all amazon apps.

https://forum.xda-developers.com/hd8-hd10/development/official-amazon-fire-toolbox-v1-0-t3889604

**Comment by mbennoer** [comment]
@lefoy Great! Will use that one once I get my HD 10 on Saturday. Thanks for sharing the link.

**Comment by SimulatedMatter** [comment]
@lefoy once you installed that what did you run to stop the delay?

**Comment by lefoy** [comment]
what delay are you talking about? I don't have any delay

**Comment by SimulatedMatter** [comment]
Okay that's good to hear. There is a delay for launcherhijack but I suppose you don't need that since this tool lets you install a custom launcher. What launcher did you go with?

**Comment by lefoy** [comment]
The tool I linked can remove the fire launcher completely (under the section Remove everything Amazon and select Manual), so you can use any launcher you want. The tool can also install Nova launcher for you (this is what I did initially, but I ended up using [this one](https://play.google.com/store/apps/details?id=com.ss.squarehome2&hl=en_CA).

I read that the launcherhijack can in fact have a small delay when pressing the home button, but with the fire launcher removed/disabled that doesn't happen. It even gives me the choice of the launcher I want to use like a normal android when I have more than one launcher installed.

**Comment by friedl** [comment]
@lefoy That's an awesome find. I'll try that on my Fire8. 

Did you find any performance improvements after removing the Amazon launcher?

**Comment by lefoy** [comment]
Can't say, I wanted to change the launcher as soon as I got my tablet. I didn't really use it with the fire launcher, but I'm having no issue using a custom launcher so far.

**Comment by SimulatedMatter** [comment]
I have some minor improvement without the Fire OS (I was previously running Nova launcher over the top of the Fire OS). This definitely works though which is nice.

**Comment by jerry4301** [comment]
I'm not a programmer so please excuse my ignorance. The problem with the 5-7 delay where the Amazon launcher comes up for 5-7 seconds after pressing the home button before reverting to the Nova Launcher appears to be caused by a Fire update. If you don't yet have the problem, I suggest you disable auto updates. I tried the Amazon Fire Toolbox recommended by lefoy and removed the Amazon launcher and Free Offers, however that causes the current screen to freeze for the 5-7 seconds upon hitting the home button before bringing up the Nova Launcher, rather than activating the Amazon launcher for that period of time.  I'm hoping that this info will assist one of you guys who is a lot smarter than me to figure out how to fix this annoying problem.

**Comment by jerry4301** [comment]
I just read on another forum that if you touch any app on the intervening Fire launcher during the 5-7 seconds the screen will immediately revert to the Nova launcher. I tried it and it's true. Makes the problem more of a minor inconvenience than a major annoyance.

**Comment by jenn-reid** [comment]
Hi!  Sorry for resurrecting the dead (post), but I wanted to post in case someone else gets here trying to solve this issue and wants a different solution to the ones above (and/or the non-existent ones elsewhere), I was having this same issue on my Amazon Fire 7, same setup/issue (Nova Launcher / pressing the home button goes to the stock fire interface then takes 5ish seconds to flip back to Nova Launcher / none of the solutions I found online helped).  I spent several days researching and trying to fix this issue, was about to attempt rooting my fire or trying the amazon fire toolbox above, when I came across this:

https://www.bountysource.com/issues/87207614-5-second-delay-after-hitting-the-home-button

Summarized the solution (for me) was to disable the user account that the stock fire launcher uses by using ADB and running:

adb shell pm disable-user --user 0 com.amazon.firelauncher

Solved the issue for me instantly.  Hopefully it will help someone else too with this super annoying issue.  If you are already familiar with ADB or already set it up to install Google Play or whatever, this is super easy.  Now my Nova Launcher is seamless :)  Hopefully this will help someone else.

**Comment by stmalk** [comment]
> 
> 
> Summarized the solution (for me) was to disable the user account that the stock fire launcher uses by using ADB and running:
> 
> adb shell pm disable-user --user 0 com.amazon.firelauncher
> 
That worked like a charm! Thank you so much, you solved that year old issue!
