### ISSUE TITLE
Launcher Hijack fails due to Accessibility Settings (FireTV Stick 4k)

### ISSUE THREAD

**Issue by kernel-panic-enjoyer** [BaronKiko/LauncherHijack#69]
**Describe the bug**
I install LauncherHijack using the method described in HELP.md
I open LauncherHijack and get the error saying that Accessibility Settings are disabled

**Expected behaviour**
I expected to be able to choose a Launcher of my choice.

**Launcher Hijack Version and Device**
LauncherHijack V4.0.3
Fire OS 6.2.6.8 (NS6268/2315)

**Logs**
```
C:\Users\user\adb>adb install "C:\Users\user\Desktop\LauncherHijackV403.apk"
4630 KB/s (1590776 bytes in 0.335s)
Success

C:\Users\user\adb>adb shell settings put secure enabled_accessibility_services com.baronkiko.launcherhijack/com.baronkiko.launcherhijack.AccServ

C:\Users\user\adb>adb shell settings put secure accessibility_enabled 1

C:\Users\user\adb>
```

**Additional context**
I am using the latest Hardware and Software of the Fire TV Stick 4k

**Comment by pJestr** [comment]
Duplicate of https://github.com/BaronKiko/LauncherHijack/issues/52

**Comment by kernel-panic-enjoyer** [comment]
Duplicate of https://github.com/BaronKiko/LauncherHijack/issues/52
