### ISSUE TITLE
Accessibility Service

### ISSUE THREAD

**Issue by z1haze** [BaronKiko/LauncherHijack#9]
what does your comment on you must enable accessibility server by going to accessibility  etc.. theres nothing to 'turn on' in here.. there's screen magnifier, high contrast text, and closed caption? Nothing says 'enable'

**Comment by BaronKiko** [comment]
Well it's pretty clear, you need to enable the accessibility service or it isn't going to work. If you follow the steps and can't find the option check you are using Amazon fire OS.
Regardless this is for bugs not your inability to set up. Go to the xda forum for help with that.
